# Generated by Django 4.2.3 on 2023-08-13 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0002_rename_producto_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursales',
            name='apellido',
        ),
    ]
