# Generated by Django 4.2.3 on 2023-08-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0003_remove_sucursales_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('empresa', models.CharField(max_length=60)),
                ('rubro', models.CharField(max_length=60)),
                ('cuit', models.IntegerField()),
                ('direccion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Rrhh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('profesion', models.CharField(max_length=60)),
                ('edad', models.IntegerField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Rrhh',
                'verbose_name_plural': 'Rrhh',
            },
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AlterModelOptions(
            name='ofertas',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='productos',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='sucursales',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
    ]
