# Generated by Django 4.2.3 on 2023-08-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0004_proveedores_rrhh_alter_empleados_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='cuit',
            field=models.IntegerField(max_length=14),
        ),
        migrations.AlterField(
            model_name='rrhh',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
