# Generated by Django 4.2.3 on 2023-08-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superapp', '0005_alter_proveedores_cuit_alter_rrhh_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedores',
            name='cuit',
            field=models.IntegerField(),
        ),
    ]
